# Generated by Django 4.2.2 on 2023-06-22 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("institution", models.CharField(max_length=200)),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Framework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("framework_name", models.CharField(max_length=200)),
                ("framework_description", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language_name", models.CharField(max_length=200)),
                ("language_documentation", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="MeasurementInstrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instrument_name", models.CharField(max_length=200)),
                ("instrument_description", models.CharField(max_length=200)),
                ("instrument_publication", models.CharField(max_length=200)),
                ("additional_details", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="ModelParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parameter_unit", models.CharField(max_length=200)),
                ("details", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="ModelVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("variable_value", models.FloatField()),
                ("variable_measurement_unit", models.CharField(max_length=200)),
                ("details", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Parameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parameter_name", models.CharField(max_length=200)),
                ("parameter_description", models.CharField(max_length=200)),
                (
                    "framework",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="models.framework",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PsychField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discipline_name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="PsychModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reviewed", models.BooleanField(default=False)),
                (
                    "slug",
                    models.SlugField(
                        editable=False, max_length=8, null=True, unique=True
                    ),
                ),
                ("model_name", models.CharField(max_length=200, unique=True)),
                ("description", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "co_authors",
                    models.ManyToManyField(
                        related_name="co_authors", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "framework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="models.framework",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="models.language",
                    ),
                ),
                (
                    "model_parameters",
                    models.ManyToManyField(
                        through="models.ModelParameter", to="models.parameter"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Variable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("variable_name", models.CharField(max_length=200)),
                ("variable_description", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="ProposedModel",
            fields=[
                (
                    "psychmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="models.psychmodel",
                    ),
                ),
            ],
            bases=("models.psychmodel",),
        ),
        migrations.CreateModel(
            name="SoftwarePackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("package_name", models.CharField(max_length=200)),
                ("package_description", models.CharField(max_length=200)),
                ("package_documentation", models.CharField(max_length=200)),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="models.language",
                    ),
                ),
                ("models", models.ManyToManyField(to="models.psychmodel")),
            ],
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unique_identifier", models.CharField(max_length=200, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("model_authors", models.ManyToManyField(to="models.author")),
            ],
        ),
        migrations.AddField(
            model_name="psychmodel",
            name="model_variables",
            field=models.ManyToManyField(
                through="models.ModelVariable", to="models.variable"
            ),
        ),
        migrations.AddField(
            model_name="psychmodel",
            name="publication",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="models.publication"
            ),
        ),
        migrations.AddField(
            model_name="psychmodel",
            name="reviewer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviewer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="psychmodel",
            name="submitting_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submitting_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="modelvariable",
            name="modelId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="models.psychmodel"
            ),
        ),
        migrations.AddField(
            model_name="modelvariable",
            name="variableId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="models.variable"
            ),
        ),
        migrations.AddField(
            model_name="modelvariable",
            name="variable_instrument",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="models.measurementinstrument",
            ),
        ),
        migrations.AddField(
            model_name="modelparameter",
            name="modelId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="models.psychmodel"
            ),
        ),
        migrations.AddField(
            model_name="modelparameter",
            name="parameterId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="models.parameter"
            ),
        ),
    ]
