# Generated by Django 4.2.2 on 2023-06-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="softwarepackage",
            name="models",
        ),
        migrations.AddField(
            model_name="psychmodel",
            name="software_package",
            field=models.ManyToManyField(to="models.softwarepackage"),
        ),
        migrations.AlterField(
            model_name="psychmodel",
            name="model_parameters",
            field=models.ManyToManyField(
                through="models.Modelparameter", to="models.parameter"
            ),
        ),
        migrations.AlterField(
            model_name="psychmodel",
            name="model_variables",
            field=models.ManyToManyField(
                through="models.Modelvariable", to="models.variable"
            ),
        ),
    ]
