# Generated by Django 4.2.2 on 2023-06-28 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0002_remove_softwarepackage_models_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="framework",
            name="parent_framework",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="models.framework",
            ),
        ),
    ]
