# Generated by Django 4.2.3 on 2023-07-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0003_framework_parent_framework"),
    ]

    operations = [
        migrations.AlterField(
            model_name="framework",
            name="framework_description",
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name="parameter",
            name="parameter_description",
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name="psychmodel",
            name="description",
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name="softwarepackage",
            name="package_description",
            field=models.CharField(max_length=1500),
        ),
    ]
