# Generated by Django 4.2.3 on 2023-07-12 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0005_publication_issue_publication_outlet_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="psychmodel",
            name="code",
            field=models.URLField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="psychmodel",
            name="data",
            field=models.URLField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="measurementinstrument",
            name="instrument_publication",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="models.publication"
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="unique_identifier",
            field=models.URLField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="softwarepackage",
            name="package_documentation",
            field=models.URLField(max_length=254),
        ),
    ]
