# Generated by Django 4.2.3 on 2023-07-14 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("models", "0006_psychmodel_code_psychmodel_data_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="psychmodel",
            old_name="code",
            new_name="codeURL",
        ),
        migrations.RemoveField(
            model_name="modelparameter",
            name="parameterId",
        ),
        migrations.RemoveField(
            model_name="modelparameter",
            name="parameter_unit",
        ),
        migrations.RemoveField(
            model_name="modelvariable",
            name="variableId",
        ),
        migrations.RemoveField(
            model_name="modelvariable",
            name="variable_instrument",
        ),
        migrations.RemoveField(
            model_name="modelvariable",
            name="variable_measurement_unit",
        ),
        migrations.RemoveField(
            model_name="modelvariable",
            name="variable_value",
        ),
        migrations.RemoveField(
            model_name="psychmodel",
            name="co_authors",
        ),
        migrations.RemoveField(
            model_name="psychmodel",
            name="data",
        ),
        migrations.RemoveField(
            model_name="psychmodel",
            name="model_parameters",
        ),
        migrations.RemoveField(
            model_name="psychmodel",
            name="model_variables",
        ),
        migrations.RemoveField(
            model_name="psychmodel",
            name="software_package",
        ),
        migrations.AddField(
            model_name="modelvariable",
            name="measurementinstrument",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="models.measurementinstrument",
            ),
        ),
        migrations.AddField(
            model_name="modelvariable",
            name="name",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="psychmodel",
            name="dataURL",
            field=models.URLField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="psychmodel",
            name="how_does_it_work",
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="institution",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="measurementinstrument",
            name="additional_details",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="measurementinstrument",
            name="instrument_description",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="modelparameter",
            name="details",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="modelvariable",
            name="details",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name="psychmodel",
            name="framework",
        ),
        migrations.AlterField(
            model_name="psychmodel",
            name="reviewer",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviewer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="psychmodel",
            name="framework",
            field=models.ManyToManyField(to="models.framework"),
        ),
    ]
