# Generated by Django 4.2.3 on 2023-07-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0007_rename_code_psychmodel_codeurl_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="psychmodel",
            name="slug",
        ),
        migrations.AddField(
            model_name="modelparameter",
            name="name",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
