# Generated by Django 4.2.3 on 2023-07-14 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0008_remove_psychmodel_slug_modelparameter_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelvariable",
            name="modelId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modelvariable",
                to="models.psychmodel",
            ),
        ),
    ]
