# Generated by Django 4.2.3 on 2023-07-15 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("models", "0009_alter_modelvariable_modelid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="institution",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="framework",
            name="framework_description",
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name="framework",
            name="parent_framework",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="models.framework",
            ),
        ),
        migrations.AlterField(
            model_name="modelparameter",
            name="modelId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modelparameters",
                to="models.psychmodel",
            ),
        ),
        migrations.AlterField(
            model_name="modelvariable",
            name="modelId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modelvariables",
                to="models.psychmodel",
            ),
        ),
        migrations.AlterField(
            model_name="psychmodel",
            name="codeURL",
            field=models.URLField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="publication",
            name="issue",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="publication",
            name="outlet",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="publication",
            name="pages",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="publication",
            name="volume",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
