# Generated by Django 4.2.3 on 2023-07-18 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0011_alter_framework_framework_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="publication",
            old_name="model_authors",
            new_name="authors",
        ),
    ]
