# Generated by Django 4.2.3 on 2023-12-01 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0012_rename_model_authors_publication_authors"),
    ]

    operations = [
        migrations.AddField(
            model_name="framework",
            name="publication",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="models.publication",
            ),
        ),
        migrations.AlterField(
            model_name="parameter",
            name="framework",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="models.framework",
            ),
        ),
    ]
