# Generated by Django 4.2.3 on 2023-12-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0014_proposal_delete_proposedmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="psychmodel",
            name="softwarepackage",
            field=models.ManyToManyField(to="models.softwarepackage"),
        ),
        migrations.AlterField(
            model_name="softwarepackage",
            name="package_description",
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name="softwarepackage",
            name="package_documentation",
            field=models.URLField(blank=True, max_length=254, null=True),
        ),
    ]
