# Generated by Django 4.2.3 on 2023-12-13 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0015_psychmodel_softwarepackage_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="softwarepackage",
            old_name="package_description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="softwarepackage",
            old_name="package_documentation",
            new_name="documentation",
        ),
        migrations.RenameField(
            model_name="softwarepackage",
            old_name="package_name",
            new_name="name",
        ),
    ]
