# Generated by Django 4.2.3 on 2024-01-30 13:10

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        (
            "models",
            "0016_rename_package_description_softwarepackage_description_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="framework",
            name="explanation",
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="psychmodel",
            name="psychfield",
            field=models.ManyToManyField(to="models.psychfield"),
        ),
    ]
