# Generated by Django 4.2.3 on 2024-03-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0017_framework_explanation_psychmodel_psychfield"),
    ]

    operations = [
        migrations.CreateModel(
            name="Behaviour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=1500)),
            ],
        ),
    ]
