# Generated by Django 4.2.3 on 2024-04-03 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0018_behaviour"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parameter",
            name="framework",
        ),
        migrations.AddField(
            model_name="measurementinstrument",
            name="variables",
            field=models.ManyToManyField(blank=True, to="models.variable"),
        ),
        migrations.AddField(
            model_name="modelvariable",
            name="variableId",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="models.variable",
            ),
        ),
        migrations.AddField(
            model_name="psychmodel",
            name="model_variables",
            field=models.ManyToManyField(
                blank=True, through="models.Modelvariable", to="models.variable"
            ),
        ),
        migrations.DeleteModel(
            name="ModelParameter",
        ),
        migrations.DeleteModel(
            name="Parameter",
        ),
    ]
