# Generated by Django 4.2.3 on 2024-05-01 09:00

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0019_remove_parameter_framework_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="psychmodel",
            name="how_does_it_work",
        ),
        migrations.AddField(
            model_name="psychmodel",
            name="explanation",
            field=markdownx.models.MarkdownxField(
                blank=True, max_length=3000, null=True
            ),
        ),
    ]
