# Generated by Django 4.2.3 on 2024-05-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0020_remove_psychmodel_how_does_it_work_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="psychmodel",
            name="how_does_it_work",
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
