# Generated by Django 4.2.3 on 2024-05-07 14:13

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0021_psychmodel_how_does_it_work"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="psychmodel",
            name="how_does_it_work",
        ),
        migrations.AlterField(
            model_name="psychmodel",
            name="explanation",
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="psychmodel",
            name="psychfield",
            field=models.ManyToManyField(blank=True, to="models.psychfield"),
        ),
        migrations.AlterField(
            model_name="psychmodel",
            name="softwarepackage",
            field=models.ManyToManyField(blank=True, to="models.softwarepackage"),
        ),
    ]
