# Generated by Django 4.2.3 on 2024-01-30 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("models", "0017_framework_explanation_psychmodel_psychfield"),
    ]

    operations = [
        migrations.CreateModel(
            name="phenomenon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phenomenon_name", models.CharField(max_length=200)),
                ("phenomenon_description", models.CharField(max_length=1500)),
                (
                    "psychfield",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="models.psychfield",
                    ),
                ),
            ],
        ),
    ]
