# Generated by Django 4.2.3 on 2024-03-21 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0018_behaviour"),
        ("facts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="phenomenon",
            old_name="phenomenon_description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="phenomenon",
            old_name="psychfield",
            new_name="field",
        ),
        migrations.RenameField(
            model_name="phenomenon",
            old_name="phenomenon_name",
            new_name="name",
        ),
        migrations.AddField(
            model_name="phenomenon",
            name="pubication",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="models.publication",
            ),
        ),
        migrations.CreateModel(
            name="Pattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=1500)),
                (
                    "behaviour",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="models.behaviour",
                    ),
                ),
                ("variables", models.ManyToManyField(blank=True, to="models.variable")),
            ],
        ),
        migrations.CreateModel(
            name="Construct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=1500)),
                (
                    "field",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="models.psychfield",
                    ),
                ),
                ("variables", models.ManyToManyField(blank=True, to="models.variable")),
            ],
        ),
        migrations.AddField(
            model_name="phenomenon",
            name="constructs",
            field=models.ManyToManyField(blank=True, to="facts.construct"),
        ),
        migrations.AddField(
            model_name="phenomenon",
            name="patterns",
            field=models.ManyToManyField(blank=True, to="facts.pattern"),
        ),
    ]
