# Generated by Django 4.2.3 on 2024-03-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facts", "0002_rename_phenomenon_description_phenomenon_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="phenomenon",
            name="short",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
