# Generated by Django 4.2.3 on 2024-03-21 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0018_behaviour"),
        ("facts", "0003_phenomenon_short"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phenomenon",
            name="field",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="models.psychfield",
            ),
        ),
        migrations.AlterField(
            model_name="phenomenon",
            name="pubication",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="models.publication",
            ),
        ),
    ]
