# Generated by Django 4.2.3 on 2024-03-26 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facts", "0004_alter_phenomenon_field_alter_phenomenon_pubication"),
    ]

    operations = [
        migrations.RenameField(
            model_name="phenomenon",
            old_name="pubication",
            new_name="publication",
        ),
    ]
