# Generated by Django 4.2.3 on 2024-04-02 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0018_behaviour"),
        ("facts", "0005_rename_pubication_phenomenon_publication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="construct",
            name="description",
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name="construct",
            name="field",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="models.psychfield",
            ),
        ),
        migrations.AlterField(
            model_name="pattern",
            name="description",
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
