# Generated by Django 4.2.3 on 2024-04-02 12:42

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0018_behaviour"),
        ("facts", "0006_alter_construct_description_alter_construct_field_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1500, null=True),
                ),
                ("data", models.URLField(blank=True, null=True)),
                (
                    "publication",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="models.publication",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="pattern",
            name="behaviour",
        ),
        migrations.RemoveField(
            model_name="pattern",
            name="variables",
        ),
        migrations.RemoveField(
            model_name="phenomenon",
            name="patterns",
        ),
        migrations.AlterField(
            model_name="phenomenon",
            name="description",
            field=markdownx.models.MarkdownxField(
                blank=True, max_length=3000, null=True
            ),
        ),
        migrations.CreateModel(
            name="Fact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("short", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1500, null=True),
                ),
                ("evidence", models.ManyToManyField(blank=True, to="facts.evidence")),
                ("patterns", models.ManyToManyField(blank=True, to="facts.pattern")),
                (
                    "phenomenon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="facts.phenomenon",
                    ),
                ),
            ],
        ),
    ]
