# Generated by Django 4.2.3 on 2024-04-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0018_behaviour"),
        ("facts", "0007_evidence_remove_pattern_behaviour_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="phenomenon",
            name="field",
        ),
        migrations.AddField(
            model_name="phenomenon",
            name="field",
            field=models.ManyToManyField(blank=True, null=True, to="models.psychfield"),
        ),
    ]
