# Generated by Django 4.2.3 on 2024-04-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0019_remove_parameter_framework_and_more"),
        ("facts", "0008_remove_phenomenon_field_phenomenon_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phenomenon",
            name="field",
            field=models.ManyToManyField(blank=True, to="models.psychfield"),
        ),
    ]
