# Generated by Django 4.2.3 on 2024-05-07 14:13

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ("facts", "0009_alter_phenomenon_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evidence",
            name="name",
        ),
        migrations.AlterField(
            model_name="evidence",
            name="description",
            field=markdownx.models.MarkdownxField(
                blank=True, max_length=1500, null=True
            ),
        ),
        migrations.AlterField(
            model_name="fact",
            name="description",
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="phenomenon",
            name="description",
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
